// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accounts struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Addresses struct {
	ID            string             `json:"id"`
	StreetAddress *string            `json:"street_address"`
	City          string             `json:"city"`
	StateProvince string             `json:"state_province"`
	PostalCode    string             `json:"postal_code"`
	Country       string             `json:"country"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AccountsID    *string            `json:"accounts_id"`
}
