// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/p-jirayusakul/go-flat-arch-template/external (interfaces: ExternalAPI)
//
// Generated by this command:
//
//	mockgen -package mockup -destination test/mockup/api.go github.com/p-jirayusakul/go-flat-arch-template/external ExternalAPI
//

// Package mockup is a generated GoMock package.
package mockup

import (
	reflect "reflect"

	external "github.com/p-jirayusakul/go-flat-arch-template/external"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalAPI is a mock of ExternalAPI interface.
type MockExternalAPI struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAPIMockRecorder
}

// MockExternalAPIMockRecorder is the mock recorder for MockExternalAPI.
type MockExternalAPIMockRecorder struct {
	mock *MockExternalAPI
}

// NewMockExternalAPI creates a new mock instance.
func NewMockExternalAPI(ctrl *gomock.Controller) *MockExternalAPI {
	mock := &MockExternalAPI{ctrl: ctrl}
	mock.recorder = &MockExternalAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalAPI) EXPECT() *MockExternalAPIMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockExternalAPI) CreatePost(arg0 external.CreatePostParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockExternalAPIMockRecorder) CreatePost(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockExternalAPI)(nil).CreatePost), arg0)
}

// GetPosts mocks base method.
func (m *MockExternalAPI) GetPosts() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockExternalAPIMockRecorder) GetPosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockExternalAPI)(nil).GetPosts))
}
