// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/p-jirayusakul/go-flat-arch-template/database/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockup -destination test/mockup/store.go github.com/p-jirayusakul/go-flat-arch-template/database/sqlc Store
//

// Package mockup is a generated GoMock package.
package mockup

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	database "github.com/p-jirayusakul/go-flat-arch-template/database/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockStore) CreateAccount(arg0 context.Context, arg1 database.CreateAccountParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStoreMockRecorder) CreateAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStore)(nil).CreateAccount), arg0, arg1)
}

// CreateAddresses mocks base method.
func (m *MockStore) CreateAddresses(arg0 context.Context, arg1 database.CreateAddressesParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAddresses indicates an expected call of CreateAddresses.
func (mr *MockStoreMockRecorder) CreateAddresses(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockStore)(nil).CreateAddresses), arg0, arg1)
}

// DeleteAccount mocks base method.
func (m *MockStore) DeleteAccount(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockStoreMockRecorder) DeleteAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockStore)(nil).DeleteAccount), arg0, arg1)
}

// DeleteAddressesById mocks base method.
func (m *MockStore) DeleteAddressesById(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddressesById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddressesById indicates an expected call of DeleteAddressesById.
func (mr *MockStoreMockRecorder) DeleteAddressesById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddressesById", reflect.TypeOf((*MockStore)(nil).DeleteAddressesById), arg0, arg1)
}

// GetAccountByEmail mocks base method.
func (m *MockStore) GetAccountByEmail(arg0 context.Context, arg1 string) (database.GetAccountByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByEmail", arg0, arg1)
	ret0, _ := ret[0].(database.GetAccountByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByEmail indicates an expected call of GetAccountByEmail.
func (mr *MockStoreMockRecorder) GetAccountByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByEmail", reflect.TypeOf((*MockStore)(nil).GetAccountByEmail), arg0, arg1)
}

// GetAccountByID mocks base method.
func (m *MockStore) GetAccountByID(arg0 context.Context, arg1 string) (database.GetAccountByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", arg0, arg1)
	ret0, _ := ret[0].(database.GetAccountByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockStoreMockRecorder) GetAccountByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockStore)(nil).GetAccountByID), arg0, arg1)
}

// GetAddressById mocks base method.
func (m *MockStore) GetAddressById(arg0 context.Context, arg1 string) (database.GetAddressByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressById", arg0, arg1)
	ret0, _ := ret[0].(database.GetAddressByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressById indicates an expected call of GetAddressById.
func (mr *MockStoreMockRecorder) GetAddressById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressById", reflect.TypeOf((*MockStore)(nil).GetAddressById), arg0, arg1)
}

// IsAccountAlreadyExists mocks base method.
func (m *MockStore) IsAccountAlreadyExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAccountAlreadyExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAccountAlreadyExists indicates an expected call of IsAccountAlreadyExists.
func (mr *MockStoreMockRecorder) IsAccountAlreadyExists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccountAlreadyExists", reflect.TypeOf((*MockStore)(nil).IsAccountAlreadyExists), arg0, arg1)
}

// IsAddressesAlreadyExists mocks base method.
func (m *MockStore) IsAddressesAlreadyExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddressesAlreadyExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAddressesAlreadyExists indicates an expected call of IsAddressesAlreadyExists.
func (mr *MockStoreMockRecorder) IsAddressesAlreadyExists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddressesAlreadyExists", reflect.TypeOf((*MockStore)(nil).IsAddressesAlreadyExists), arg0, arg1)
}

// IsEmailAlreadyExists mocks base method.
func (m *MockStore) IsEmailAlreadyExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmailAlreadyExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmailAlreadyExists indicates an expected call of IsEmailAlreadyExists.
func (mr *MockStoreMockRecorder) IsEmailAlreadyExists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmailAlreadyExists", reflect.TypeOf((*MockStore)(nil).IsEmailAlreadyExists), arg0, arg1)
}

// ListAccounts mocks base method.
func (m *MockStore) ListAccounts(arg0 context.Context) ([]database.ListAccountsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", arg0)
	ret0, _ := ret[0].([]database.ListAccountsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockStoreMockRecorder) ListAccounts(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockStore)(nil).ListAccounts), arg0)
}

// ListAddresses mocks base method.
func (m *MockStore) ListAddresses(arg0 context.Context) ([]database.ListAddressesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddresses", arg0)
	ret0, _ := ret[0].([]database.ListAddressesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddresses indicates an expected call of ListAddresses.
func (mr *MockStoreMockRecorder) ListAddresses(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddresses", reflect.TypeOf((*MockStore)(nil).ListAddresses), arg0)
}

// ListAddressesByAccountId mocks base method.
func (m *MockStore) ListAddressesByAccountId(arg0 context.Context, arg1 pgtype.Text) ([]database.ListAddressesByAccountIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddressesByAccountId", arg0, arg1)
	ret0, _ := ret[0].([]database.ListAddressesByAccountIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddressesByAccountId indicates an expected call of ListAddressesByAccountId.
func (mr *MockStoreMockRecorder) ListAddressesByAccountId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddressesByAccountId", reflect.TypeOf((*MockStore)(nil).ListAddressesByAccountId), arg0, arg1)
}

// UpdateAccountPasswordByEmail mocks base method.
func (m *MockStore) UpdateAccountPasswordByEmail(arg0 context.Context, arg1 database.UpdateAccountPasswordByEmailParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountPasswordByEmail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountPasswordByEmail indicates an expected call of UpdateAccountPasswordByEmail.
func (mr *MockStoreMockRecorder) UpdateAccountPasswordByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountPasswordByEmail", reflect.TypeOf((*MockStore)(nil).UpdateAccountPasswordByEmail), arg0, arg1)
}

// UpdateAddressById mocks base method.
func (m *MockStore) UpdateAddressById(arg0 context.Context, arg1 database.UpdateAddressByIdParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddressById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddressById indicates an expected call of UpdateAddressById.
func (mr *MockStoreMockRecorder) UpdateAddressById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddressById", reflect.TypeOf((*MockStore)(nil).UpdateAddressById), arg0, arg1)
}
